typography_spectrum: 0.5332754156552255
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.1732962627429515
  lightness: 0.9028461796697229
  saturation: 0.5389106897637248
  rhythmicContrast: 0.7646176649723202
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9396220957860351
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/dc2360de-b486-4c9d-b2e6-3a52f872a712.jpg
name: AmZecTravel
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ca068621-cd8a-4330-9156-0f7f86e47f9a.jpg
purpose: []
